theme: minima
title: Michael's Blog
author: Michael Wu
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
There is nothing to see or do here yet

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
